myList =[]
print(myList)
myList.append(10)
myList.append(20)
myList.append(30)
myList.append(40)
print("List after append:",myList)
myList.insert(1,15)
print("List after insert:",myList)
myList.extend([50,60,70])
print("List after extend:",myList)
myList.remove(myList[-1])
print("List after remove:",myList)
myList.sort()
print("List after sort:",myList)
print("Index of 30:",myList.index(30))  
